spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarymanagementsystem
    username: root
    password: Missing_Voyager#2441139qwert

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
